CREATE DATABASE SELLMNG;

USE SELLMNG;

CREATE TABLE CUSTOMER(
cID VARCHAR(50) PRIMARY KEY,
cName VARCHAR(50) NOT NULL,
cAge INT);

CREATE TABLE ORDERS(
oID VARCHAR(50) PRIMARY KEY,
cID VARCHAR(50) NOT NULL,
oDate DATE ,
oTotalPrice FLOAT,
FOREIGN KEY (cID) REFERENCES CUSTOMER (cID));

CREATE TABLE PRODUCT(
pID VARCHAR(50) PRIMARY KEY,
pName VARCHAR(50) NOT NULL,
pPrice FLOAT DEFAULT 0);

CREATE TABLE ORDERDETAIL(
oID VARCHAR(50) NOT NULL,
pID VARCHAR(50) NOT NULL,
odQTY VARCHAR(50),
PRIMARY KEY(oID, pID),
FOREIGN KEY (oID) REFERENCES ORDERS ( oID),
FOREIGN KEY (pID) REFERENCES PRODUCT (pID));