CREATE DATABASE STUDENTMNG;

USE STUDENTMNG;

CREATE TABLE CLASS(
ClassID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
ClassName VARCHAR(60) NOT NULL,
StartDate DATETIME NOT NULL,
Status BIT);

CREATE TABLE STUDENT(
StudentID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
StudentName VARCHAR(30) NOT NULL,
Address VARCHAR(50),
Phone VARCHAR(20),
Status BIT,
ClassID INT NOT NULL,
FOREIGN KEY (ClassID) REFERENCES Class (ClassID));

CREATE TABLE SUBJECT(
SubID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
SubName VARCHAR(30) NOT NULL,
Credit TINYINT NOT NULL DEFAULT 1
CHECK (Credit >=1),
Status BIT DEFAULT 1);

CREATE TABLE MARK(
MarkID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
SubID INT NOT NULL,
StudentID INT NOT NULL,
Mark FLOAT DEFAULT 0 
CHECK (Mark BETWEEN 0 AND 100),
ExamTimes TINYINT DEFAULT 1,
UNIQUE ( SubID, StudentID),
FOREIGN KEY ( SubID) REFERENCES SUBJECT (SubID),
FOREIGN KEY ( StudentID ) REFERENCES STUDENT (StudentID));